"""add_payment_tables_uuid

Revision ID: a238ca2ed9fd
Revises: 0009_teacher_access_codes
Create Date: 2026-05-09 21:18:17.986045

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'a238ca2ed9fd'
down_revision = '0009_teacher_access_codes'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_prices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('original_price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('is_free', sa.Boolean(), nullable=False),
    sa.Column('discount_percentage', sa.Integer(), nullable=False),
    sa.Column('discount_valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_prices_course_id'), 'course_prices', ['course_id'], unique=True)
    op.create_index(op.f('ix_course_prices_id'), 'course_prices', ['id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', 'REFUNDED', name='paymentstatus'), nullable=False),
    sa.Column('payment_method', sa.Enum('RAZORPAY', 'STRIPE', 'PAYPAL', 'UPI', 'CARD', 'NET_BANKING', name='paymentmethod'), nullable=True),
    sa.Column('razorpay_order_id', sa.String(length=255), nullable=True),
    sa.Column('razorpay_payment_id', sa.String(length=255), nullable=True),
    sa.Column('razorpay_signature', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('receipt', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_course_id'), 'payments', ['course_id'], unique=False)
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_razorpay_order_id'), 'payments', ['razorpay_order_id'], unique=True)
    op.create_index(op.f('ix_payments_razorpay_payment_id'), 'payments', ['razorpay_payment_id'], unique=True)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.drop_table('v2_teacher_settings')
    op.drop_index(op.f('ix_v2_mock_tests_teacher_id'), table_name='v2_mock_tests')
    op.drop_table('v2_mock_tests')
    op.drop_index(op.f('ix_v2_resources_subject'), table_name='v2_resources')
    op.drop_index(op.f('ix_v2_resources_teacher_id'), table_name='v2_resources')
    op.drop_index(op.f('ix_v2_resources_type'), table_name='v2_resources')
    op.drop_table('v2_resources')
    op.drop_index(op.f('ix_v2_announcements_subject'), table_name='v2_announcements')
    op.drop_index(op.f('ix_v2_announcements_teacher_id'), table_name='v2_announcements')
    op.drop_table('v2_announcements')
    op.drop_index(op.f('ix_v2_doubts_status'), table_name='v2_doubts')
    op.drop_index(op.f('ix_v2_doubts_student_id'), table_name='v2_doubts')
    op.drop_index(op.f('ix_v2_doubts_subject'), table_name='v2_doubts')
    op.drop_table('v2_doubts')
    op.drop_index(op.f('ix_v2_assignment_submissions_assignment_id'), table_name='v2_assignment_submissions')
    op.drop_index(op.f('ix_v2_assignment_submissions_student_id'), table_name='v2_assignment_submissions')
    op.drop_table('v2_assignment_submissions')
    op.drop_index(op.f('ix_v2_live_classes_subject'), table_name='v2_live_classes')
    op.drop_index(op.f('ix_v2_live_classes_teacher_id'), table_name='v2_live_classes')
    op.drop_table('v2_live_classes')
    op.drop_index(op.f('ix_v2_question_bank_subject'), table_name='v2_question_bank')
    op.drop_index(op.f('ix_v2_question_bank_teacher_id'), table_name='v2_question_bank')
    op.drop_table('v2_question_bank')
    op.drop_table('v2_gamification')
    op.drop_index(op.f('ix_v2_chat_messages_student_id'), table_name='v2_chat_messages')
    op.drop_table('v2_chat_messages')
    op.drop_index(op.f('ix_v2_practice_sessions_student_id'), table_name='v2_practice_sessions')
    op.drop_table('v2_practice_sessions')
    op.drop_index(op.f('ix_v2_content_plans_teacher_id'), table_name='v2_content_plans')
    op.drop_table('v2_content_plans')
    op.drop_index(op.f('ix_v2_assignments_teacher_id'), table_name='v2_assignments')
    op.drop_table('v2_assignments')
    op.drop_index(op.f('ix_v2_revision_queue_student_id'), table_name='v2_revision_queue')
    op.drop_table('v2_revision_queue')
    op.drop_index(op.f('ix_users_device_id'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_device_id'), 'users', ['device_id'], unique=False)
    op.create_table('v2_revision_queue',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('question_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('subject', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('topic', sa.VARCHAR(length=200), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('explanation', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('review_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('next_review_at', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('v2_revision_queue_pkey'))
    )
    op.create_index(op.f('ix_v2_revision_queue_student_id'), 'v2_revision_queue', ['student_id'], unique=False)
    op.create_table('v2_assignments',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('teacher_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=220), autoincrement=False, nullable=False),
    sa.Column('subject', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('questions', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=False),
    sa.Column('due_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], name=op.f('v2_assignments_teacher_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('v2_assignments_pkey'))
    )
    op.create_index(op.f('ix_v2_assignments_teacher_id'), 'v2_assignments', ['teacher_id'], unique=False)
    op.create_table('v2_content_plans',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('teacher_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('subject', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=220), autoincrement=False, nullable=False),
    sa.Column('week_number', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('topics', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=False),
    sa.Column('target_date', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('v2_content_plans_pkey'))
    )
    op.create_index(op.f('ix_v2_content_plans_teacher_id'), 'v2_content_plans', ['teacher_id'], unique=False)
    op.create_table('v2_practice_sessions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('subject', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('topic', sa.VARCHAR(length=200), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('questions_answered', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('correct', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('current_difficulty', sa.INTEGER(), server_default=sa.text('3'), autoincrement=False, nullable=False),
    sa.Column('ended', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('v2_practice_sessions_pkey'))
    )
    op.create_index(op.f('ix_v2_practice_sessions_student_id'), 'v2_practice_sessions', ['student_id'], unique=False)
    op.create_table('v2_chat_messages',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('subject', sa.VARCHAR(length=80), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('v2_chat_messages_pkey'))
    )
    op.create_index(op.f('ix_v2_chat_messages_student_id'), 'v2_chat_messages', ['student_id'], unique=False)
    op.create_table('v2_gamification',
    sa.Column('student_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=120), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('xp', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('streak_days', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('last_active_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('badges', sa.VARCHAR(length=500), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('student_id', name=op.f('v2_gamification_pkey'))
    )
    op.create_table('v2_question_bank',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('teacher_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('subject', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('topic', sa.VARCHAR(length=200), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('question_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('options', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('correct_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('explanation', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('difficulty', sa.INTEGER(), server_default=sa.text('3'), autoincrement=False, nullable=False),
    sa.Column('tags', sa.VARCHAR(length=300), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=20), server_default=sa.text("'manual'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('v2_question_bank_pkey'))
    )
    op.create_index(op.f('ix_v2_question_bank_teacher_id'), 'v2_question_bank', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_v2_question_bank_subject'), 'v2_question_bank', ['subject'], unique=False)
    op.create_table('v2_live_classes',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('teacher_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('teacher_name', sa.VARCHAR(length=120), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=220), autoincrement=False, nullable=False),
    sa.Column('subject', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('meet_link', sa.VARCHAR(length=500), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('starts_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('duration_min', sa.INTEGER(), server_default=sa.text('60'), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'scheduled'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('v2_live_classes_pkey'))
    )
    op.create_index(op.f('ix_v2_live_classes_teacher_id'), 'v2_live_classes', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_v2_live_classes_subject'), 'v2_live_classes', ['subject'], unique=False)
    op.create_table('v2_assignment_submissions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('assignment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('answers', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'::json"), autoincrement=False, nullable=False),
    sa.Column('score', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('total', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('submitted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['v2_assignments.id'], name=op.f('v2_assignment_submissions_assignment_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('v2_assignment_submissions_student_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('v2_assignment_submissions_pkey'))
    )
    op.create_index(op.f('ix_v2_assignment_submissions_student_id'), 'v2_assignment_submissions', ['student_id'], unique=False)
    op.create_index(op.f('ix_v2_assignment_submissions_assignment_id'), 'v2_assignment_submissions', ['assignment_id'], unique=False)
    op.create_table('v2_doubts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('student_name', sa.VARCHAR(length=120), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('subject', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('topic', sa.VARCHAR(length=200), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('question', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('answer', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('answered_by_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('answered_by_name', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('upvotes', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'open'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('answered_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('v2_doubts_pkey'))
    )
    op.create_index(op.f('ix_v2_doubts_subject'), 'v2_doubts', ['subject'], unique=False)
    op.create_index(op.f('ix_v2_doubts_student_id'), 'v2_doubts', ['student_id'], unique=False)
    op.create_index(op.f('ix_v2_doubts_status'), 'v2_doubts', ['status'], unique=False)
    op.create_table('v2_announcements',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('teacher_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('teacher_name', sa.VARCHAR(length=120), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('subject', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=220), autoincrement=False, nullable=False),
    sa.Column('body', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('priority', sa.VARCHAR(length=20), server_default=sa.text("'normal'::character varying"), autoincrement=False, nullable=False),
    sa.Column('pinned', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('v2_announcements_pkey'))
    )
    op.create_index(op.f('ix_v2_announcements_teacher_id'), 'v2_announcements', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_v2_announcements_subject'), 'v2_announcements', ['subject'], unique=False)
    op.create_table('v2_resources',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('teacher_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('subject', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('topic', sa.VARCHAR(length=200), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=220), autoincrement=False, nullable=False),
    sa.Column('resource_type', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(length=600), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('tags', sa.VARCHAR(length=300), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('v2_resources_pkey'))
    )
    op.create_index(op.f('ix_v2_resources_type'), 'v2_resources', ['resource_type'], unique=False)
    op.create_index(op.f('ix_v2_resources_teacher_id'), 'v2_resources', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_v2_resources_subject'), 'v2_resources', ['subject'], unique=False)
    op.create_table('v2_mock_tests',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('teacher_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=220), autoincrement=False, nullable=False),
    sa.Column('subject', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('duration_min', sa.INTEGER(), server_default=sa.text('60'), autoincrement=False, nullable=False),
    sa.Column('total_marks', sa.INTEGER(), server_default=sa.text('180'), autoincrement=False, nullable=False),
    sa.Column('negative_marking', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('questions', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=False),
    sa.Column('is_published', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('v2_mock_tests_pkey'))
    )
    op.create_index(op.f('ix_v2_mock_tests_teacher_id'), 'v2_mock_tests', ['teacher_id'], unique=False)
    op.create_table('v2_teacher_settings',
    sa.Column('teacher_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=120), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('bio', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('notification_doubts', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('notification_submissions', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('notification_announcements', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('default_difficulty', sa.INTEGER(), server_default=sa.text('3'), autoincrement=False, nullable=False),
    sa.Column('auto_publish_ai_questions', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('teacher_id', name=op.f('v2_teacher_settings_pkey'))
    )
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_razorpay_payment_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_razorpay_order_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_course_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_course_prices_id'), table_name='course_prices')
    op.drop_index(op.f('ix_course_prices_course_id'), table_name='course_prices')
    op.drop_table('course_prices')
    # ### end Alembic commands ###

